language: node_js
node_js:
    - 'lts/*'
dist: trusty
sudo: false

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

cache:
    directories:
        - node_modules

addons:
    chrome: stable

script:
    - npm run build
    - xvfb-run npm run e2e

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

env:
    global:
        - CC_TEST_REPORTER_ID=a4744593ad5018b15bca45ab4cea95eccbec2bc106e6ce1b47d3be3924ebaf27

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/my-awesome-project
    on:
        branch: master
