language: node_js
node_js:
    - 'lts/*'
dist: trusty
sudo: false

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

cache:
    directories:
        - node_modules

addons:
    chrome: stable

script:
    - npm run lint
    - npm run test:headless
    - npm run build
    - xvfb-run npm run e2e

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/loreplotter
    on:
        branch: master
